# Generated by Django 4.2.7 on 2023-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_category_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('A25', 'A25_1Bed'), ('A01', 'A01_2Beds'), ('A19', 'A19_2Beds')], max_length=3),
        ),
    ]
