# Generated by Django 4.2.7 on 2023-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('A25', 'Apt 25 1Bed'), ('A01', 'Apt 01 2Beds'), ('A19', 'Apt 19 2Beds')], max_length=3),
        ),
    ]
